server {
    listen 80;
    server_name fips.cc www.fips.cc;

    location ~ /.well-known/acme-challenge {
        allow all;
    }

    location / {
        proxy_pass http://localhost:50001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 443 ssl;
    server_name fips.cc www.fips.cc;

    ssl_certificate /root/shuqi/janus/nginx/ssl/janus.crt;
    ssl_certificate_key /root/shuqi/janus/nginx/ssl/janus.key;

    location / {
        proxy_pass http://localhost:50001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
